Update FoldersCreator.ts
When I get a Timeout (while uploading), I get the following error:
spsave: GotError: connect ETIMEDOUT 13.107.136.9:443

And then, I got a similar error to #67:
TypeError: Cannot read property 'statusCode' of undefined

Because:
promise.reason in undefined


I can handle the Timeout-Error, but I cannot handle the TypeError.